package com.ricko.passwordmanager.Controller;

import com.ricko.passwordmanager.Repository.DataRepository;
import com.ricko.passwordmanager.Repository.UserRepository;
import com.ricko.passwordmanager.Service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

@Controller
public class MainController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private UserRepository userRepo;

    @Autowired
    private DataRepository dataRepo;


    @GetMapping("/data")
    public String data(String success, Model model){
        if(success!=null)
            model.addAttribute("success","New position added succesfully");

        model.addAttribute("data",userService.getCurrentUserData());
        return "/data/data";
    }

    @GetMapping("/data/add")
    public String dataForm(){
        return "data/dataForm";
    }


    @Autowired
    UserService userService;

    @PostMapping("/data/add")
    public String addData(@RequestParam String site,@RequestParam String password, Model model){

        //String result;
        /*userRepo.findById(1).ifPresent(
                customer -> dataRepo.save(new Data(site,password,customer))
        );*/
        try{
            userService.currentUserAddData(site, password);
            model.addAttribute("success","New position added succesfully");
        } catch (Exception e) {
            //e.printStackTrace();
            model.addAttribute("error", "Error - couldn't add new position");
        }

        return "/data/data";
    }


}
